name: Deploy E-commerce App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Update app di EC2
            if [ ! -d "aws-ecommerce" ]; then
              git clone https://github.com/ardiansyahmuhammad/ecommerce-product-dev-ardi.git

            cd aws-ecommerce
            git pull origin main
            pip3 install -r requirements.txt

            # Kill app lama kalau ada
            sudo pkill -f "python3 app.py" || true

            # Run app baru di background
            nohup sudo python3 app.py > app.log 2>&1 &
