name: Deploy to EC2 Frontend Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ecommerce-app || git clone https://github.com/ardiansyahmuhammad/ecommerce-product-dev-ardi.git

            cd ecommerce-app
            git pull origin main
            pip3 install -r requirements.txt
            sudo pkill python3 || true
            sudo nohup python3 app.py > app.log 2>&1 &
