name: Deploy E-commerce App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Update system and install required packages
            sudo yum update -y
            sudo yum install -y git python3-pip

            # Clone repo if not exist
            if [ ! -d "ecommerce-product-dev-ardi" ]; then
              git clone git@github.com:ardiansyahmuhammad/ecommerce-product-dev-ardi.git
            fi

            # Navigate into project directory
            cd ecommerce-product-dev-ardi

            # Pull latest code
            git pull origin main

            # Install Python dependencies
            pip3 install --user -r requirements.txt

            # Kill previous running app if any
            sudo pkill -f "python3 app.py" || true

            # Run app in background using nohup
            nohup python3 app.py > app.log 2>&1 &
